"""Add firebase_token to tablettes

Revision ID: 23c2c69235e8
Revises: a9cba29009dd
Create Date: 2025-04-07 15:14:28.602822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '23c2c69235e8'
down_revision: Union[str, None] = 'a9cba29009dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sessions', 'heure_deconnexion',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('sessions', 'nombre_commande_creer',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('sessions', 'nombre_commande_traiter',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('tablettes', sa.Column('firebase_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tablettes', 'firebase_token')
    op.alter_column('sessions', 'nombre_commande_traiter',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('sessions', 'nombre_commande_creer',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('sessions', 'heure_deconnexion',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###
