"""Suppression de date_impression

Revision ID: 9b90b6e75e68
Revises: 620b85bf2598
Create Date: 2025-03-20 13:36:39.209328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9b90b6e75e68'
down_revision: Union[str, None] = '620b85bf2598'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('commandes', 'date_reception',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('commandes', 'date_impression')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commandes', sa.Column('date_impression', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.alter_column('commandes', 'date_reception',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###
