"""l'ajout de constraint unique sur numero_serie

Revision ID: be0ff9bf94c4
Revises: 9b90b6e75e68
Create Date: 2025-03-21 10:37:53.229994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be0ff9bf94c4'
down_revision: Union[str, None] = '9b90b6e75e68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'tablettes', ['numero_serie'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tablettes', type_='unique')
    # ### end Alembic commands ###
