name: SonarQube Analysis Windows

on:
  push:
    branches: [main]
  pull_request:

jobs:
  sonarqube:
    runs-on: windows-latest  # Utilise le runner Windows
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Download and Install SonarScanner
        shell: powershell
        run: |
          # Télécharger SonarScanner
          $scannerUrl = "https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-windows.zip"
          $downloadPath = "$env:RUNNER_TEMP\sonar-scanner.zip"
          Invoke-WebRequest -Uri $scannerUrl -OutFile $downloadPath
          
          # Extraire et installer
          Expand-Archive -Path $downloadPath -DestinationPath "$env:RUNNER_TEMP"
          $scannerDir = Get-ChildItem -Path "$env:RUNNER_TEMP" -Directory -Filter "sonar-scanner-*" | Select-Object -First 1
          $scannerPath = "$($scannerDir.FullName)\bin"
          
          # Ajouter au PATH
          echo "$scannerPath" | Out-File -FilePath $env:GITHUB_PATH -Append -Encoding utf8
          
          # Vérifier l'installation
          sonar-scanner.bat --version

      - name: Run SonarQube Analysis
        shell: cmd
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          sonar-scanner.bat ^
            -Dsonar.projectKey=rfc_callcenter_api_main ^
            -Dsonar.projectName="My Windows Project" ^
            -Dsonar.sources=. ^
            -Dsonar.exclusions="**/*.min.js,**/*.min.css,**/node_modules/**" ^
            -Dsonar.host.url=%SONAR_HOST_URL% ^
            -Dsonar.login=%SONAR_TOKEN% ^
            -Dsonar.sourceEncoding=UTF-8

      - name: Upload Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: sonarqube-results
          path: .scannerwork/
