name: SonarQube Analysis with Python

on:
  push:
    branches: [main]
  pull_request:

jobs:
  analyze:
    runs-on: ubuntu-latest  # Recommandé pour une meilleure compatibilité Python
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install requests pyyaml

      - name: Run SonarQube analysis (Python)
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://7376-41-223-51-170.ngrok-free.app
        run: |
          python -c "
          import os
          import requests
          from urllib.parse import quote

          # Configuration
          project_key = 'rfc_callcenter_api_main'
          sources_path = '.'
          exclusions = '**/*.min.js,**/*.min.css,**/node_modules/**'

          # 1. Trigger SonarQube analysis
          scan_cmd = f'sonar-scanner \
            -Dsonar.projectKey={project_key} \
            -Dsonar.sources={sources_path} \
            -Dsonar.exclusions={exclusions} \
            -Dsonar.host.url={os.environ["SONAR_HOST_URL"]} \
            -Dsonar.login={os.environ["SONAR_TOKEN"]}'
          os.system(scan_cmd)

          # 2. Generate security report
          api_url = f'{os.environ["SONAR_HOST_URL"]}/api/issues/search?componentKeys={project_key}&types=VULNERABILITY'
          response = requests.get(api_url, auth=(os.environ["SONAR_TOKEN"], ''))
          issues = response.json().get('issues', [])

          with open('security_report.md', 'w') as f:
              f.write('# SonarQube Security Report\n\n')
              for issue in issues:
                  f.write(f'## {issue["message"]}\n')
                  f.write(f'- **File**: {issue["component"]}\n')
                  f.write(f'- **Line**: {issue["line"]}\n')
                  f.write(f'- **Severity**: {issue["severity"]}\n\n')
          "

      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: sonarqube-python-report
          path: security_report.md
